services:
  flask-app:
    container_name: note-api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12349:12349"
    restart: unless-stopped
    networks:
      - note-api-network

networks:
  note-api-network:
    driver: bridge